# Generated by Django 5.1.4 on 2024-12-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
